// Motor spacer -- 16 mm bolt pattern, 2 mm thick
// Generated by generate_spacer.py; edit the parameters and re-render (F6).

thickness   = 2;   // plate thickness
pattern     = 16;   // hole spacing, centre to centre (adjacent holes)
screw_d     = 3.3;  // clearance hole for M3
pad_d       = 7.5;  // boss diameter around each screw
bore_d      = 12.4; // open centre
web_w       = 3;   // narrowest material between bore and outside
$fn         = 180;

bolt_r    = sqrt(2)*pattern/2;
pad_r     = pad_d/2;
bore_r    = bore_d/2;
reach     = bore_r + web_w;
px        = bolt_r*cos(45);
py        = bolt_r*sin(45);
k         = pad_r - reach;
scallop_d = (px*px + py*py - k*k) / (2*px + 2*k);
scallop_r = scallop_d - reach;
core_r    = bolt_r + pad_r - 2.7;   // filler disc, hidden under the real outline

linear_extrude(height = thickness)
difference() {
    union() {
        circle(r = core_r);
        for (a = [45:90:315]) translate([bolt_r*cos(a), bolt_r*sin(a)]) circle(r = pad_r);
    }
    for (a = [0:90:270])
        translate([scallop_d*cos(a), scallop_d*sin(a)]) circle(r = scallop_r);
    circle(r = bore_r);
    for (a = [45:90:315])
        translate([bolt_r*cos(a), bolt_r*sin(a)]) circle(d = screw_d);
}
